server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-market
    username: postgres
    password:

  rabbitmq:
    port: 5672
    host: localhost
    
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

queue-name: user_order_queue

from-mail:
